### ISSUE TITLE
AttributeError: 'module' object has no attribute 'list'

### ISSUE THREAD

**Issue by macmichael01** [PressLabs/silver#322]
My team is getting the following error when trying to perform the initial migration: 

```
./manage.py migrate silver 
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/silver/models.py", line 42, in <module>
    from international.models import countries, currencies
  File "/Users/jasonsparks/Desktop/wizevalue/.venv/lib/python2.7/site-packages/international/models.py", line 480, in <module>
    locales = babel.localedata.list()
AttributeError: 'module' object has no attribute 'list'
```

**Comment by macmichael01** [comment]
The temporary solution for now is to perform a `pip uninstall Babel` on your project. There is something that appears to be broken with django-international.

**Comment by bogdanpetrea** [comment]
Hi @macmichael01, thanks for reporting the error!
You may try using an older version of babel. It has been updated many times since the last update to django-international (~beginning of 2014).

**Comment by calind** [comment]
This should be fixed by replacing django-international (follow #324)
