### ISSUE TITLE
Version 0.1.4 does not install via pip

### ISSUE THREAD

**Issue by oucsaw** [PressLabs/silver#351]
Running:

```
pip install django-silver
```
results in the error:
```
 Running setup.py (path:/tmp/pip-build-soMSk8/django-silver/setup.py) egg_info for package django-silver
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-soMSk8/django-silver/setup.py", line 52, in <module>
        for line in open("requirements/common.txt").readlines()
    IOError: [Errno 2] No such file or directory: 'requirements/common.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-soMSk8/django-silver/setup.py", line 52, in <module>

    for line in open("requirements/common.txt").readlines()

IOError: [Errno 2] No such file or directory: 'requirements/common.txt'

```

This seems to be because `setup.py` wants to read the file 'requirements/common.txt' (line 51) which isn't present in the distributed tarball.

Apologies for not offering a fix, but my packaging foo is really not upto this. Apologies,  too if this is the wrong place to report such issues

**Comment by krodyrobi** [comment]
@oucsaw can you check if the version 0.1.4.1 works for you? And I apologize for the inconvenience.

**Comment by oucsaw** [comment]
Many thanks! Version 0.1.4.1  now installs cleanly.

Thank you for the quick turn around !
