### ISSUE TITLE
Transaction clean() method is only called through API usage

### ISSUE THREAD

**Issue by t-ionut** [PressLabs/silver#417]
As a consequence, no associated document is actually enforced

```
>>> t = Transaction()
>>> t.amount = 30
>>> t.payment_method = p
>>> t.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/silver/silver/models/transactions.py", line 185, in post_transaction_save
    send_transaction_email(instance)
  File "/silver/silver/mail.py", line 36, in send_transaction_email
    transaction.provider.name
  File "/silver/silver/models/transactions.py", line 154, in provider
    return self.document.provider
AttributeError: 'NoneType' object has no attribute 'provider'
```

I'm guessing in this scenario I should've gotten the validation error found [here](https://github.com/PressLabs/silver/blob/master/silver/models/transactions.py#L103), which I didn't

**Comment by t-ionut** [comment]
After looking a bit in the Django source code, I've noticed that `clean()` is meant to be called manually, something that @bogdanpetrea took care of in the serializers, so this issue is reduced to this question: **Should we also consider enforcing documents when added without the API?** That would mean moving the constraints from `clean()` to another place.
